### ISSUE TITLE
Via point doesn't show up

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CourseraVLSICAD#24]
```
3
1
  1  0  4
  1  1  4
  1  2  4
  1  2  3
  1  2  2
  1  2  1
  1  2  0
0
2
  1  2  3
  3  2  3  <- a via
  2  2  3
  2  3  3
0
3
  2  2  1
  2  3  1
  2  4  1
  2  5  1
  2  5  0
0
```

![image](https://f.cloud.github.com/assets/54414/373263/a9b2aacc-a37c-11e2-85e6-5c05ca4fb293.png)

**Comment by vazexqi** [comment]
```
2
  1  2  3 
  3  2  3  <- a via
  2  2  3
  2  3  3
0
```

![Screen Shot 2013-04-12 at 10 36 08 AM](https://f.cloud.github.com/assets/54414/373659/0df10dda-a387-11e2-9a65-88df9e09dfe8.png)

The problem is that we cannot see that spot since it directly penetrates the previous/next layer without moving. It just moves down/up and it is impossible to visualize it using a 2D image. Need some special marker.

**Comment by iveney** [comment]
I think something like a X mark should be good enough, or X mark inside a square.

**Comment by vazexqi** [comment]
![Screen Shot 2013-04-12 at 1 53 02 PM](https://f.cloud.github.com/assets/54414/374600/55cf4278-a3a2-11e2-9d7a-c80f666d0f24.png)

**Comment by vazexqi** [comment]
![Screen Shot 2013-04-12 at 1 57 49 PM](https://f.cloud.github.com/assets/54414/374626/e4f7547c-a3a2-11e2-8593-b9a1184b44b0.png)

Of course, this also means that **all** via points are also colored.
