### ISSUE TITLE
Toggle different non-unit cost layers?

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CourseraVLSICAD#26]
From Ivan: Suggesting a feature: highlight non-unit cost grids. e.g., use different level of gray color to show the cost. The higher, the darker. This is from benchmark3 (I updated it such that the blocks in two layers don't overlap),
we can see the router cleverly switch to layer2 to do the routing (with a small via cost).

![image](https://f.cloud.github.com/assets/54414/373285/24c38cd6-a37d-11e2-9da9-5fdcd699cfe9.png)

**When the via cost is high**:

![image](https://f.cloud.github.com/assets/54414/373287/3083f506-a37d-11e2-9d1d-fd2aeaf1e21a.png)

**Comment by iveney** [comment]
The feature should be very useful, and having more control such as a toggle is always good. 

That said, it will even be better to have toggle to show/hide a layer (or even route!) If this is done then probably you can sell it for money :p

**Comment by vazexqi** [comment]
@iveney : Is there a range for the non-unit cost? Does it go from 0 - 100? Or 0 - 50? Or it cannot be determined?

**Comment by vazexqi** [comment]
![Screen Shot 2013-04-12 at 6 18 00 PM](https://f.cloud.github.com/assets/54414/375640/44f55d0a-a3c7-11e2-96aa-2a876fe5a4cf.png)
