### ISSUE TITLE
Add marks to denote source and sink points

### ISSUE THREAD

**Issue by iveney** [vazexqi/CourseraVLSICAD#27]
Something like this.

![image](https://f.cloud.github.com/assets/51033/374158/ac3e3310-a395-11e2-9ec7-ea262458b163.png)

**Comment by vazexqi** [comment]
I am probably going to use one of the symbols from d3 directly. See https://github.com/mbostock/d3/wiki/SVG-Shapes#wiki-symbol_type.

Incidentally since there is a square and circle I will use those.

**Comment by iveney** [comment]
That can probably also be used for Vias.

After a second thought, circle and square are not so contrasting, so probably use circle and triangle? Just try a few different combinations and pick a good pair...

**Comment by vazexqi** [comment]
![Screen Shot 2013-04-12 at 4 16 25 PM](https://f.cloud.github.com/assets/54414/375218/42b94292-a3b6-11e2-8b53-c511416f6fb4.png)

Right now I am using just squares and try to differentiate by color. I am not sure if we need to introduce so many symbols so I just distinguish start and end using colors.

We can change this easily. Let me know.

**Comment by vazexqi** [comment]
Also, symmetric shapes work best, .e.g, circles, square, etc because they don't imply a direction. I used a triangle and it looks weird when the direction of the line doesn't match the pointed direction of the triangle.
